spring:
  application:
    name: AlarmScheduler
  graphql:
    graphiql:
      enabled: true
    path: /graphql
  datasource:
    url: jdbc:h2:mem:alarmsdb
    driver-class-name: org.h2.Driver
    username: Teste
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true